version: '3.8'

services:
  # Serviço 1: Banco de Dados MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'wordpress_db'
      MYSQL_USER: 'wp_user'
      MYSQL_PASSWORD: 'wp_password'
    networks:
      - app-network

  # Serviço 2: Aplicação WordPress (COM A CORREÇÃO)
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    depends_on:
      - mysql
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_USER: 'wp_user'
      WORDPRESS_DB_PASSWORD: 'wp_password'
      WORDPRESS_DB_NAME: 'wordpress_db'
      # --- LINHAS ADICIONADAS PARA CORRIGIR O REDIRECIONAMENTO ---
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost/prova');
        define('WP_SITEURL', 'http://localhost/prova');
    networks:
      - app-network

  # Serviço 3: Gerenciador do Banco de Dados
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_manager
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root_password'
    networks:
      - app-network

  # Serviço 4: Proxy Reverso Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

# Define os volumes nomeados e a rede customizada
volumes:
  db_data:
  wp_files:

networks:
  app-network:
    driver: bridge